#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Dragon Fly ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Dragon Fly ConfigğŸ’»
#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 1.0'
ConfigVersion: '1.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#âœâœâœâœâœPermissionsâœâœâœâœâœ
#dragonFly.Admin > Grants access to /dragonfly commands
#dragonFly.Reload > Reloads the plugin *(You must also have dragonFly.Admin)*
#dragonFly.Adminfly > Grants access to use the free adminfly command *(You must also have dragonFly.Admin)*
#dragonFly.Toggle.Others > Ability to toggle other players flight *(You must also have dragonFly.Admin)*
#dragonFly.Use > Grants access to /fly command
#dragonFly.Fuel > Uses fuel blocks to fly *(You must also have dragonFly.Use)*
#dragonFly.NoFuel > Free flight *(You must also have dragonFly.Use)*
#âœâœâœâœâœPermissionsâœâœâœâœâœ

#####You can Modify the following how you wish#####
#â™¢â™¢â™¢â™¢â™¢Fuel Blockâ™¢â™¢â™¢â™¢â™¢
Fuel: 'REDSTONE'

#â™¢â™¢â™¢â™¢â™¢ Amount of time for fuel to last (In game ticks [20 ticks = 1 second]) â™¢â™¢â™¢â™¢â™¢
#â˜ â˜ â˜ â˜  WARNING: You must restart the server for this to take effect.â˜ â˜ â˜ â˜ 
Fuel-Time: 60

#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/EHm6Ra3K
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default file.