#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Dragon Fly ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Dragon Fly ConfigğŸ’»
#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 2.0'
ConfigVersion: '2.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#âœâœâœâœâœPermissionsâœâœâœâœâœ

#Player permissions
#â˜ â˜ â˜ â˜ ##WARNING: DO NOT GIVE THE SAME PLAYER OR GROUP  "dragonFly.Fuel" and "dragonFly.NoFuel"
#THIS WILL CONFUSE THE PLUGIN AND MAY CAUSE IT TO NOT WORK PROPPERLY#â˜ â˜ â˜ â˜ ##
#dragonFly.Use > Grants access to /fly command
#dragonFly.Fuel > Uses fuel blocks to fly *(You must also have dragonFly.Use)*
#dragonFly.NoFuel > Free flight *(You must also have dragonFly.Use)*

#Admin Permissions
#dragonFly.Admin > Grants access to /dragonfly commands
#dragonFly.Reload > Reloads the plugin *(You must also have dragonFly.Admin)*
#dragonFly.Adminfly > Grants access to use the free adminfly command *(You must also have dragonFly.Admin)*
#dragonFly.Toggle.Others > Ability to toggle other players flight *(You must also have dragonFly.Admin)*
#âœâœâœâœâœPermissionsâœâœâœâœâœ

#####You can Modify the following how you wish#####
#â™¢â™¢â™¢â™¢â™¢Fuel Blockâ™¢â™¢â™¢â™¢â™¢
#â˜ â˜ â˜ â˜  You must use single quotes '' as seen in this default config.â˜ â˜ â˜ â˜ 
# This is the item that is being used to allow them to fly, All material types can be used.
# You can find a list of materials here > https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
Fuel: 'REDSTONE'

#â™¢â™¢â™¢â™¢â™¢ Amount of time for fuel to last (In game ticks [20 ticks = 1 second]) â™¢â™¢â™¢â™¢â™¢
#â˜ â˜ â˜ â˜  WARNING: You must restart the server for this to take effect.â˜ â˜ â˜ â˜ 
Fuel-Time: 60

#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/EHm6Ra3K
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default config file.